### ISSUE TITLE
Proposal: Ducky

### ISSUE THREAD

**Issue by lyledavids** [kaiachain/kaia-dapp-mono#108]
Description
- A on-chain art creator. Users can create on-chain art and mint it as an NFT

Bounty track
- NFT

**Comment by zxstim** [comment]
Approved. Can you paste deployment links, github repos and so on into here? You can use one of those free platform like vercel or cloudflare pages to deploy your app.

**Comment by lyledavids** [comment]
Github repo - https://github.com/lyledavids/duckykaia
Dorahacks - https://dorahacks.io/buidl/15797

**Comment by lyledavids** [comment]
In future, when adding new features and improvements, do I need to notify you on github as well?

**Comment by zxstim** [comment]
> In future, when adding new features and improvements, do I need to notify you on github as well?

i will close this issue soon for payout. So when you make updates, just open a new issue. I probably need to add an update template.

> Github repo - https://github.com/lyledavids/duckykaia

Can you deploy this so i can use and assign a bounty amount? Don't have to buy a domain or anything. Cloudflare pages or vercel allows you to connect your github repo to their platform and deploy to their domain for free.

Also, i see the smart contract address [`0x05d0aca3ba12f010f6a26104da5cb83419723842`](https://kairos.kaiascan.io/address/0x05d0aca3ba12f010f6a26104da5cb83419723842?tabId=txList&page=1), can you share the contract code as well?

**Comment by lyledavids** [comment]
Current nft contract and future contracts can be found here - https://github.com/lyledavids/duckykaia/tree/main/contracts
Will move from using Remix to Hardhat soon so there will be changes in the repo

Deployment - https://duckykaia.netlify.app/

**Comment by zxstim** [comment]
Cool. Give me a day or 2 to sort out the payment.

**Comment by zxstim** [comment]
Ok interesting. I think your URI metadata is mis-configured that's why it's not rendering on explorer. My tx has the correct input (https://kairos.kaiascan.io/tx/0x72042d38d806855774d17413db315629589f082f377c398ae42c8eaf7d043a99?tabId=inputData&page=1).

Double check your token URI, or override it if needed. Check out a tutorial for onchain nft here:
https://docs.base.org/tutorials/complex-onchain-nfts/

Be mindful of svg image size, maybe do a check for that.

I will approve for `900 KLAY` payout for this. It's very promising but need a lot more work.

Also, I recommend using Vite (instead of Create React App because your hot-reload will get significantly longer as your project gets bigger) and adopt Wagmi + RainbowKit for managing wallet interactions rather than writing everything manually yourself (it would work but it would take a lot longer for you to handle tx life cycle). I am ok with "raw UI" but I want great UX.

**Comment by zxstim** [comment]
Closing this issue ready for payout

**Comment by zxstim** [comment]
Also, please create a PR and add yourself to the `hall-of-fame.md` file here:
https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/hall-of-fame.md

**Comment by lyledavids** [comment]
> Ok interesting. I think your URI metadata is mis-configured that's why it's not rendering on explorer. My tx has the correct input (https://kairos.kaiascan.io/tx/0x72042d38d806855774d17413db315629589f082f377c398ae42c8eaf7d043a99?tabId=inputData&page=1).

> Also, I recommend using Vite (instead of Create React App because your hot-reload will get significantly longer as your project gets bigger) and adopt Wagmi + RainbowKit for managing wallet interactions rather than writing everything manually yourself (it would work but it would take a lot longer for you to handle tx life cycle). I am ok with "raw UI" but I want great UX.

I noticed the issue with token URI, have sorted it out

I'm moving things over into Scaffold-ETH2, they have everything pre-configured

**Comment by lyledavids** [comment]
Are there any other alternatives for data besides Subquery?

**Comment by zxstim** [comment]
it depends on your use case but check here: https://github.com/kaiachain/awesome-kaia

and here: https://www.kaia.io/ecosystem

make a new issue when you are ready to submit again
